tekst = "pierwszy tekst"
print(tekst)
print("\n" + tekst + " + nast tekst")
print(tekst.upper())
print(tekst.isupper())
print(tekst.islower())
print(tekst.upper().isupper())
print(len(tekst))
print(tekst[2])
#print(tekst.index("S"))
print(tekst.index('i'))